name: Generate Resources & Deploy GitHub Pages
on:
  push:
    branches:
        - websitetest

jobs:

    deploy:
        runs-on: ubuntu-latest

    
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
              python-version: 3.x
          - run: |
              pip install mkdocs-material mkdocs-material-extensions
              pip install mkdocs-include-dir-to-nav
              pip install pillow cairosvg
          - name: Deploy
            working-directory: Docs
            run: mkdocs gh-deploy --force
