name: regenerateDocs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Import PSCloudPC module
        shell: pwsh
        run: |
          Import-Module ./Src/PSCloudPC.psm1
      - name: Install Microsoft.PowerShell.PlatyPS module
        shell: pwsh
        run: |
          Install-Module -Name Microsoft.PowerShell.PlatyPS -Force
      - name: Publishing module
        shell: pwsh
        run: |
          Import-Module Microsoft.PowerShell.PlatyPS -Force
          New-MarkdownHelp -Module "PSCloudPC" -OutputFolder ".\Docs" -Force