name: regenerateDocs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install platyPS module
        shell: pwsh
        run: |
          Install-Module -Name platyPS -Force
          ls
      - name: Regenerate Docs
        shell: pwsh
        run: |
          Import-Module platyPS -Force
          Import-Module ./PSCloudPC/Src/PSCloudPC.psm1 -Force
          New-MarkdownHelp -Module "PSCloudPC" -OutputFolder "./PSCloudPC/Docs" -Force
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
      # - name: Pull request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     commit-message: "Regenerated Docs."
      #     branch: 'regeneratedocs'
      #     title: "Regenerated Docs"
      #     body: "This PR was created automatically to regenerate the documentation."
      #     base: 'main'